name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Somente na branch main
  pull_request:
    branches:
      - main   # Somente na branch main

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: meubanco
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
      - name: Wait for PostgreSQL to be ready
        run: |
          sudo apt-get install -y netcat
          until nc -z -v -w30 127.0.0.1 5432; do
            echo "Waiting for database connection..."
            sleep 5
          done
      - name: Run tests
        run: |
          pytest backend/tests/

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run tests
        run: |
          cd frontend
          npm test

  deploy:
    if: github.ref == 'refs/heads/main'  # Só executa o deploy quando a branch for main
    runs-on: ubuntu-latest
    steps:
      - name: Request approval before deploying
        uses: peter-evans/manual-approval-action@v1
        with:
          approval_required: true  # Aprovação manual antes do deploy
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy?key=${{ secrets.RENDER_API_KEY }}"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
